SyncCodeServer/urls.py
from tkinter.font import names

from django.contrib import admin
from django.urls import path
from django.shortcuts import redirect
from web.views import server, project, task, admin, account, home

urlpatterns = [
    # path("admin/", admin.site.urls),

    # 默认展示页面路径
    path("", lambda request: redirect("home_show")),
    path("home/", home.home_show, name='home_show'),

    # 服务器管理
    path("server/list/", server.server_list, name='server_list'),
    path("server/add/", server.server_add, name='server_add'),

    # <int:nid>用来匹配到url中的内容(ID)
    path("server/edit/<int:nid>/", server.server_edit, name='server_edit'),
    path("server/delete/<int:nid>/", server.server_delete, name='server_delete'),
    path("server/multi/", server.server_multi, name='server_multi'),

    # 项目管理
    path("project/list/", project.project_list, name='project_list'),
    path("project/add/", project.project_add, name='project_add'),
    path("project/edit/<int:nid>/", project.project_edit, name='project_edit'),
    path("project/delete/<int:nid>/", project.project_delete, name='project_delete'),

    # 任务管理
    path("task/list/<int:project_id>/", task.task_list, name='task_list'),
    path("task/add/<int:project_id>/", task.task_add, name='task_add'),
    path("task/delete/<int:nid>/", task.task_delete, name='task_delete'),
    path("hook/template/<int:tid>/", task.hook_template, name='hook_template'),
    path("deploy/<int:task_id>/", task.deploy, name='deploy'),

    # 管理员
    path('admin/list/', admin.admin_list, name='admin_list'),
    path('admin/add/', admin.admin_add, name='admin_add'),
    path('admin/<int:nid>/edit/', admin.admin_edit, name='admin_edit'),
    path('admin/<int:nid>/delete/', admin.admin_delete, name='admin_delete'),
    path('admin/<int:nid>/reset/', admin.admin_reset, name='admin_reset'),

    # 登录
    path('login/', account.login, name='login'),
    path('logout/', account.logout, name='logout'),
    path('image/code/', account.image_code, name='image_code'),

]

web/models.py
from django.db import models


# Create your models here.

# 服务器表
class Server(models.Model):
    hostname = models.CharField(verbose_name='主机名', max_length=128)

    def __str__(self):
        return self.hostname


# 项目表
class Project(models.Model):
    title = models.CharField(verbose_name='项目名称', max_length=256)
    # 项目所在仓库 https://github.com/xxx/xxx
    repo = models.CharField(verbose_name='仓库地址', max_length=256)

    env_choices = (
        ('prod', '生产环境'),
        ('test', '测试环境'),
    )
    env = models.CharField(verbose_name='环境', max_length=128, choices=env_choices, default='test')

    path = models.CharField(verbose_name='线上项目路径', max_length=256)
    servers = models.ManyToManyField(verbose_name='关联服务器', to='Server')

    def __str__(self):
        return "%s-%s" % (self.title, self.get_env_display())


# 发布任务表
class DeployTask(models.Model):
    uid = models.CharField(verbose_name='标识', max_length=64)
    project = models.ForeignKey(verbose_name='项目环境', to='Project', on_delete=models.CASCADE)
    tag = models.CharField(verbose_name='版本号', max_length=128)

    status_choices = (
        (1, '待发布'),
        (2, '发布中'),
        (3, '成功'),
        (4, '失败'),
    )
    status = models.IntegerField(verbose_name='状态', choices=status_choices, default=1)

    before_download_script = models.TextField(verbose_name='下载前脚本', null=True, blank=True)
    after_download_script = models.TextField(verbose_name='下载后脚本', null=True, blank=True)
    before_deploy_script = models.TextField(verbose_name='发布前脚本', null=True, blank=True)
    after_deploy_script = models.TextField(verbose_name='发布后脚本', null=True, blank=True)


# 钩子模板
class HookTemplate(models.Model):
    title = models.CharField(verbose_name="标题", max_length=32)
    content = models.TextField(verbose_name='脚本内容')

    hook_type_choices = (
        (2, '下载前'),
        (4, '下载后'),
        (6, '发布前'),
        (8, '发布后'),
    )
    hook_type = models.IntegerField(verbose_name='钩子类型', choices=hook_type_choices)


# 发布节点
class Node(models.Model):
    task = models.ForeignKey(verbose_name='发布任务单', to='DeployTask', on_delete=models.CASCADE)

    text = models.CharField(verbose_name='节点文字', max_length=32)
    status_choices = [
        ("lightgray", '待发布'),
        ("green", '成功'),
        ("red", '失败'),
    ]
    status = models.CharField(verbose_name='状态', max_length=16, choices=status_choices, default='lightgray')
    parent = models.ForeignKey(verbose_name='父节点', to='self', null=True, blank=True, on_delete=models.CASCADE)
    server = models.ForeignKey(verbose_name='服务器', to='Server', null=True, blank=True, on_delete=models.CASCADE)


class Admin(models.Model):
    """ 管理员表 """
    username = models.CharField(verbose_name='用户名', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=64)
    phone = models.CharField(verbose_name='手机号', max_length=32)
    email = models.CharField(verbose_name='邮箱', max_length=32)

    # 返回模型的字符串表示形式，即用户名
    # 当调用 str() 方法时，会返回管理员的用户名
    def __str__(self):
        return self.username

web/forms/task.py
import datetime
from os import environ
from web.forms.base import BootStrapModelForm
from web import models
from django import forms


class TaskModelForm(BootStrapModelForm):
    exclude_bootstrap = [
        "before_download_template",
        "after_download_template",
        'before_deploy_template',
        'after_deploy_template'
    ]

    before_download_select = forms.ChoiceField(required=False, label='下载前')
    before_download_title = forms.CharField(required=False, label='模板名称')
    before_download_template = forms.BooleanField(required=False, widget=forms.CheckboxInput, label='是否保存为模板')

    after_download_select = forms.ChoiceField(required=False, label='下载后')
    after_download_title = forms.CharField(required=False, label='模板名称')
    after_download_template = forms.BooleanField(required=False, widget=forms.CheckboxInput, label='是否保存为模板')

    before_deploy_select = forms.ChoiceField(required=False, label='发布前')
    before_deploy_title = forms.CharField(required=False, label='模板名称')
    before_deploy_template = forms.BooleanField(required=False, widget=forms.CheckboxInput, label='是否保存为模板')

    after_deploy_select = forms.ChoiceField(required=False, label='下载后')
    after_deploy_title = forms.CharField(required=False, label='模板名称')
    after_deploy_template = forms.BooleanField(required=False, widget=forms.CheckboxInput, label='是否保存为模板')

    class Meta:
        model = models.DeployTask
        # fields = "__all__"
        exclude = ['uid', 'project', 'status']

    def __init__(self, project_object, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.project_object = project_object

        self.init_hook()

    def init_hook(self):
        before_download = [(0, '请选择'), ]
        before_download.extend(models.HookTemplate.objects.filter(hook_type=2).values_list('id', 'title'))
        self.fields['before_download_select'].choices = before_download

        after_download = [(0, '请选择'), ]
        after_download.extend(models.HookTemplate.objects.filter(hook_type=4).values_list('id', 'title'))
        self.fields['after_download_select'].choices = after_download

        before_deploy = [(0, '请选择'), ]
        before_deploy.extend(models.HookTemplate.objects.filter(hook_type=6).values_list('id', 'title'))
        self.fields['before_deploy_select'].choices = before_deploy

        after_deploy = [(0, '请选择'), ]
        after_deploy.extend(models.HookTemplate.objects.filter(hook_type=8).values_list('id', 'title'))
        self.fields['after_deploy_select'].choices = after_deploy

    def save(self, commit=True):
        # 保存: 当前任务发布单的表
        self.instance.uid = self.create_uid()
        self.instance.project_id = self.project_object.id
        super().save(commit)

        # 模板钩子
        if self.cleaned_data.get('before_download_template'):
            title = self.cleaned_data.get('before_download_title')
            content = self.cleaned_data.get('before_download_script')
            models.HookTemplate.objects.create(title=title, content=content, hook_type=2)

        if self.cleaned_data.get('after_download_template'):
            title = self.cleaned_data.get('after_download_title')
            content = self.cleaned_data.get('after_download_script')
            models.HookTemplate.objects.create(title=title, content=content, hook_type=4)

        if self.cleaned_data.get('before_deploy_template'):
            title = self.cleaned_data.get('before_deploy_title')
            content = self.cleaned_data.get('before_deploy_script')
            models.HookTemplate.objects.create(title=title, content=content, hook_type=6)

        if self.cleaned_data.get('after_deploy_template'):
            title = self.cleaned_data.get('after_deploy_title')
            content = self.cleaned_data.get('after_deploy_script')
            models.HookTemplate.objects.create(title=title, content=content, hook_type=8)

    def create_uid(self):
        title = self.project_object.title
        env = self.project_object.env
        tag = self.cleaned_data.get('tag')
        date = datetime.datetime.now().strftime('%Y%m%d%H%M%S')
        return "{0}-{1}-{2}-{3}".format(title, env, tag, date)

    def clean(self):
        if self.cleaned_data.get('before_download_template'):
            title = self.cleaned_data.get('before_download_title')
            if not title:
                self.add_error("before_download_title", '请输入模板名称')

        if self.cleaned_data.get('after_download_template'):
            title = self.cleaned_data.get('after_download_title')
            if not title:
                self.add_error("after_download_title", '请输入模板名称')

        if self.cleaned_data.get('before_deploy_template'):
            title = self.cleaned_data.get('before_deploy_title')
            if not title:
                self.add_error("before_deploy_title", '请输入模板名称')

        if self.cleaned_data.get('after_deploy_template'):
            title = self.cleaned_data.get('after_deploy_title')
            if not title:
                self.add_error("after_deploy_title", '请输入模板名称')

web/views/account.py
from django.shortcuts import render, HttpResponse, redirect
from django import forms
from io import BytesIO

from web.utils.code import check_code
from web import models
from web.utils.bootstrap import BootStrapForm
from web.utils.encrypt import md5


class LoginForm(BootStrapForm):
    username = forms.CharField(
        label="用户名",
        widget=forms.TextInput,
        required=True
    )
    password = forms.CharField(
        label="密码",
        widget=forms.PasswordInput(render_value=True),
        required=True
    )

    code = forms.CharField(
        label="验证码",
        widget=forms.TextInput,
        required=True
    )

    def clean_password(self):
        pwd = self.cleaned_data.get("password")
        return md5(pwd)


def login(request):
    """ 登录 """
    if request.method == "GET":
        form = LoginForm()
        return render(request, 'login.html', {'form': form})

    form = LoginForm(data=request.POST)
    if form.is_valid():
        # 验证成功，获取到的用户名和密码
        # {'username': 'wupeiqi', 'password': '123',"code":123}
        # {'username': 'wupeiqi', 'password': '5e5c3bad7eb35cba3638e145c830c35f',"code":xxx}

        # 验证码的校验
        user_input_code = form.cleaned_data.pop('code')
        code = request.session.get('image_code', "")
        if code.upper() != user_input_code.upper():
            form.add_error("code", "验证码错误")
            return render(request, 'login.html', {'form': form})

        # 去数据库校验用户名和密码是否正确，获取用户对象、None
        # admin_object = models.Admin.objects.filter(username=xxx, password=xxx).first()
        admin_object = models.Admin.objects.filter(**form.cleaned_data).first()
        if not admin_object:
            form.add_error("password", "用户名或密码错误")
            # form.add_error("username", "用户名或密码错误")
            return render(request, 'login.html', {'form': form})

        # 用户名和密码正确
        # 网站生成随机字符串; 写到用户浏览器的cookie中；在写入到session中；
        request.session["info"] = {'id': admin_object.id, 'name': admin_object.username}
        # session可以保存7天
        request.session.set_expiry(60 * 60 * 24 * 7)

        return redirect("/home/")

    return render(request, 'login.html', {'form': form})


def image_code(request):
    """ 生成图片验证码 """

    # 调用pillow函数，生成图片
    img, code_string = check_code()

    # 写入到自己的session中（以便于后续获取验证码再进行校验）
    request.session['image_code'] = code_string
    # 给Session设置60s超时
    request.session.set_expiry(60)

    stream = BytesIO()
    img.save(stream, 'png')
    return HttpResponse(stream.getvalue())


def logout(request):
    """ 注销 """

    request.session.clear()

    return redirect('/login/')

web/views/task.py
from django.shortcuts import HttpResponse, render, redirect
from web.forms.task import TaskModelForm
from django.http import JsonResponse
from django.urls import reverse
from web import models
from web.utils.pagination import Pagination


def task_list(request, project_id):
    queryset = models.DeployTask.objects.filter(project_id=project_id).all()
    project_object = models.Project.objects.filter(id=project_id).first()
    # 分页
    page_object = Pagination(request, queryset)
    context = {
        'project_object': project_object,
        'queryset': page_object.page_queryset,
        'page_string': page_object.html(),
    }

    return render(request, 'task_list.html', context)


def task_add(request, project_id):
    project_object = models.Project.objects.filter(id=project_id).first()

    if request.method == 'GET':
        form = TaskModelForm(project_object)
        return render(request, 'task_form.html', {'form': form, 'project_object': project_object})
    form = TaskModelForm(project_object, data=request.POST)
    if form.is_valid():
        # 重写了save方法
        form.save()
        # return redirect('/task/list/%s' % project_id)
        url = reverse('task_list', kwargs={'project_id': project_id})
        return redirect(url)
    return render(request, 'task_form.html', {'form': form, 'project_object': project_object})


def hook_template(request, tid):
    hook_template_object = models.HookTemplate.objects.filter(id=tid).first()
    return JsonResponse({'status': True, 'content': hook_template_object.content})


def deploy(request, task_id):
    task_object = models.DeployTask.objects.filter(id=task_id).first()

    return render(request, 'deploy.html', {'task_object': task_object})


def task_delete(request, nid):
    models.DeployTask.objects.filter(id=nid).delete()
    return JsonResponse({"status": True})

web/templates/admin_list.html
{% extends 'layout.html' %}

{% block title %}管理员管理{% endblock %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px" class="clearfix">
            <a class="btn btn-success" href="/admin/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建管理员
            </a>

            <div style="float: right;width: 300px;">
                <form method="get">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="用户名"
                               value="{{ search_data }}">
                        <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                      </span>
                    </div>
                </form>
            </div>

        </div>
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                靓号列表
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>用户名</th>
                    <th>密码</th>
                    <th>电话号码</th>
                    <th>邮箱地址</th>
                    <th>重置密码</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <th>{{ obj.id }}</th>
                        <td>{{ obj.username }}</td>
                        <td>*******</td>
                        <td>{{ obj.phone }}</td>
                        <td>{{ obj.email }}</td>
                        <td>
                            <a href="/admin/{{ obj.id }}/reset/">重置密码</a>
                        </td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/admin/{{ obj.id }}/edit/">编辑</a>
                            <a class="btn btn-danger btn-xs" href="/admin/{{ obj.id }}/delete/">删除</a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
        <div class="clearfix">
            <ul class="pagination">
                {{ page_string }}
            </ul>

        </div>

    </div>
{% endblock %}

web/templates/change.html
{% extends 'layout.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}

    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> {{ title }} </h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red;">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">提 交</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

web/templates/deploy.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}发布任务{% endblock %}

{% block content %}
    <div class="container">
        <h1>channles发布</h1>
        <input type="button" class="btn btn-primary" style="margin-bottom: 5px" value="初始化图标"
               onclick="createDiagram()"/>
        <input type="button" class="btn btn-primary" style="margin-bottom: 5px" value="代码发布" onclick="doDeploy()">

        <div class="panel panel-default">
            <div class="panel-heading"> 发布基本信息</div>
            <div class="panel-body">
                <table class="table table-bordered">

                    <tbody>
                    <tr>
                        <td>项目名称:{{ task_object.project.title }}</td>
                        <td>环境:{{ task_object.project.get_env_display }}</td>
                    </tr>
                    <tr>
                        <td>版本:{{ task_object.tag }}</td>
                        <td>状态:{{ task_object.get_status_display }}</td>
                    </tr>
                    <tr>
                        <td colspan="2">仓库地址:{{ task_object.project.repo }}</td>
                    </tr>
                    <tr>
                        <td colspan="2">线上路径:{{ task_object.project.path }}</td>
                    </tr>

                    <tr>
                        <td colspan="2">
                            <div>关联服务器</div>
                            <ul>
                                {% for item in task_object.project.servers.all %}
                                    <li>{{ item }}</li>
                                {% endfor %}
                            </ul>
                        </td>
                    </tr>
                    </tbody>
                </table>
                <div id="content" style="height:350px; background-color: #DAE4E4;"></div>
            </div>
        </div>

    </div>
{% endblock %}


{% block js %}
    <script src="{% static "js/go.js" %}"></script>

    <script>
        var diagram;
        var ws;

        // jquery 功能当页面加载完毕后自动执行代码块中函数
        $(function () {
            initDiagram();
            initWebSocket();
        });


        function initDiagram() {

            if (typeof go === 'undefined') {
                console.error("GoJS is not loaded.");
                return;
            }

            var $ = go.GraphObject.make;
            diagram = $(go.Diagram, "content", {
                layout: $(go.TreeLayout, {
                    angle: 0,
                    nodeSpacing: 20,
                    layerSpacing: 70
                })
            });

            diagram.nodeTemplate = $(go.Node, "Auto",
                $(go.Shape, {
                    figure: "RoundedRectangle",
                    fill: 'lightgray',
                    stroke: 'lightgray'
                }, new go.Binding("figure", "figure"), new go.Binding("fill", "color"), new go.Binding("stroke", "color")),
                $(go.TextBlock, {margin: 8}, new go.Binding("text", "text"))
            );

            diagram.linkTemplate = $(go.Link,
                {routing: go.Link.Orthogonal},
                $(go.Shape, {stroke: 'lightgray'}, new go.Binding('stroke', 'link_color')),
                $(go.Shape, {toArrow: "OpenTriangle", stroke: 'lightgray'}, new go.Binding('stroke', 'link_color'))
            );

            /*
            var nodeDataArray = [
                {key: "start", text: '开始', figure: 'Ellipse', color: "lightgreen"},
                {key: "download", parent: 'start', text: '下载代码', color: "lightgreen", link_text: '执行中...'},
                {key: "compile", parent: 'download', text: '本地编译', color: "lightgreen"},
                {key: "zip", parent: 'compile', text: '打包', color: "red", link_color: 'red'},
                {key: "c1", text: '服务器1', parent: "zip"},
                {key: "c11", text: '服务重启', parent: "c1"},
                {key: "c2", text: '服务器2', parent: "zip"},
                {key: "c21", text: '服务重启', parent: "c2"},
                {key: "c3", text: '服务器3', parent: "zip"},
                {key: "c31", text: '服务重启', parent: "c3"}
            ];
            diagram.model = new go.TreeModel(nodeDataArray);
            */
        }

        function initWebSocket() {
            ws = new WebSocket('ws://127.0.0.1:8000/publish/{{ task_object.id }}/');

            ws.onmessage = function (event) {
                var result = JSON.parse(event.data);
                if (result.code === 'init') {
                    console.log(result)
                    diagram.model = new go.TreeModel(result.data);
                } else if (result.code === "update") {
                    // 更新节点颜色：node_id:1,color:green
                    var node = diagram.model.findNodeDataForKey(result.node_id);
                    diagram.model.setDataProperty(node, "color", result.color);
                }
            }
        }

        function createDiagram() {
            ws.send("init")
        }

        function doDeploy() {
            ws.send('deploy')
        }
    </script>
{% endblock %}

web/templates/form.html
{% extends 'layout.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}

    <div class="container">
        <form class="form-horizontal" method="post" novalidate>
            {% csrf_token %}
            {% for foo in form %}
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">{{ foo.label }}</label>
                    <div class="col-sm-10">
                        {{ foo }}
                        <span style="color: red">{{ foo.errors.0 }}</span>
                    </div>
                </div>
            {% endfor %}

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-success">提 交</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

web/templates/home_show.html
{% extends 'layout.html' %}

{% block title %}代码发布系统{% endblock %}

{% block content %}
    <h1>代码发布系统</h1>
{% endblock %}

web/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}代码发布系统{% endblock %}</title>
    {% block css %}

    {% endblock %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}">
</head>
<body>
<div>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home_show' %}">代码发布系统</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'server_list' %}">服务器管理</a></li>
                    <li><a href="{% url 'project_list' %}">项目管理</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'admin_list' %}">管理员列表</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">
                            <i class="glyphicon glyphicon-user"></i>

                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="#">{{ request.session.info.name }}</a></li>
                            <li><a href="{% url 'logout' %}">注销</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
</div>
<div>
    {% block content %}{% endblock %}
</div>

<script src="{% static 'js/jquery-3.7.1.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1-dist/js/bootstrap.min.js' %}"></script>
{% block js %}

{% endblock %}
</body>
</html>

web/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录页面</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <style>
        .account {
            width: 400px;
            border: 1px solid #dddddd;
            border-radius: 5px;
            box-shadow: 5px 5px 20px #aaa;

            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;
            padding: 20px 40px;
        }

        .account h2 {
            margin-top: 10px;
            text-align: center;
        }
    </style>
</head>
<body>
<div class="account">
    <h2>用户登录</h2>
    <h3>用户名: admin</h3>
    <h3>密码: admin</h3>
    <form method="post" novalidate>
        {% csrf_token %}
        <div class="form-group">
            <label>用户名</label>
            {{ form.username }}
            <span style="color: red;">{{ form.username.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label>密码</label>
            {{ form.password }}
            <span style="color: red;">{{ form.password.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label for="id_code">图片验证码</label>
            <div class="row">
                <div class="col-xs-7">
                    {{ form.code }}
                    <span style="color: red;">{{ form.code.errors.0 }}</span>
                </div>
                <div class="col-xs-5">
                    <img id="image_code" src="/image/code/" style="width: 125px;">
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-8"><input type="submit" value="登 录" class="btn btn-primary"></div>
            <div class="col-md-4"><input type="button" onclick="location.reload()" value="刷新验证码" class="btn btn-info"></div>
        </div>

    </form>
</div>

<script src="{% static 'js/jquery-3.7.1.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1-dist/js/bootstrap.min.js' %}"></script>
</body>
</html>

web/templates/task_list.html
{% extends 'layout.html' %}

{% block title %}任务管理{% endblock %}

{% block content %}
    <div class="container">
        <h1>发布任务单: ( {{ project_object.title }} - {{ project_object.get_env_display }} )</h1>
        <div>
            <a style="margin: 10px 0" href="{% url 'task_add' project_id=project_object.id %}" class="btn btn-primary">添加</a>
        </div>
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>标识</th>
                <th>状态</th>
                <th>操作</th>
                <th>删除</th>
            </tr>
            </thead>
            <tbody>

            {% for row in queryset %}
                <tr>
                    <th>{{ row.id }}</th>
                    <th>{{ row.uid }}</th>
                    <th>{{ row.get_status_display }}</th>
                    <th>
                        <a href="{% url 'deploy' task_id=row.id %}">发布</a>
                    </th>
                    <th>
                        <a onclick="removeRow(this, {{ row.id }});">删除</a>
                    </th>
                </tr>
            {% endfor %}

            {% block js %}
                <script>
                    function removeRow(ths, nid) {
                        let result = confirm('确认删除吗?');
                        console.log(result);
                        if (result) {
                            $.ajax({
                                url: '/task/delete/' + nid + '/',
                                type: 'GET',
                                data: 'nid',
                                dataType: 'JSON',
                                success: function (res) {
                                    if (res.status) {
                                        $(ths).parent().parent().remove();
                                    }
                                }
                            })

                        }
                    }
                </script>
            {% endblock %}
            </tbody>
        </table>

        <!-- 分页条 -->
        {% for obj in queryset %}
            {{ obj.xx }}
        {% endfor %}

        <ul class="pagination">
            {{ page_string }}
        </ul>
    </div>

{% endblock %}